[package]
name = "robusta-term"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
cgmath = "0.18.0"
clap = { version = "4.4.14", features = ["derive"] }
clap_complete = "4.4.6"
dxf = { version = "0.5.0", features = ["serialize"] }
serde = "1.0.195"
