[package]
name = "robusta-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = "0.5.1"
bevy_render = "0.13.0"
nalgebra = { version = "0.32.3", features = ["serde"] }
